name: ci /cd
on: 
  push:
    branches:
      - qa 
    paths:
      - .github/workflows/main.yml

jobs:
  gitleask-scan:
    name: Git leak scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Run Gitleask scan
        run: | 
          docker run --rm \
            -v ${{ github.workspace }}:/repo \
            zricethezav/gitleaks:latest detect \ 
            --source=/repo \
            --report-format=json \
            --report-path=/repo/gitleaks-report.json \ 
            --redact \
            --exit-code 0
      - name: Upload gitleak scan report
        uses: actions/upload-artifact@v4
        with:
          name: git-scan-report
          path: gitleaks-report.json
          if-no-file-found: warn
